/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StoresRouteImport } from './routes/stores'
import { Route as ShoppingTripRouteImport } from './routes/shopping-trip'
import { Route as ManagerRouteImport } from './routes/manager'
import { Route as GroceryListRouteImport } from './routes/grocery-list'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ManagerLoginRouteImport } from './routes/manager.login'
import { Route as ManagerStoreNameRouteImport } from './routes/manager.$storeName'

const StoresRoute = StoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => rootRouteImport,
} as any)
const ShoppingTripRoute = ShoppingTripRouteImport.update({
  id: '/shopping-trip',
  path: '/shopping-trip',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerRoute = ManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => rootRouteImport,
} as any)
const GroceryListRoute = GroceryListRouteImport.update({
  id: '/grocery-list',
  path: '/grocery-list',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerLoginRoute = ManagerLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerStoreNameRoute = ManagerStoreNameRouteImport.update({
  id: '/$storeName',
  path: '/$storeName',
  getParentRoute: () => ManagerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/grocery-list': typeof GroceryListRoute
  '/manager': typeof ManagerRouteWithChildren
  '/shopping-trip': typeof ShoppingTripRoute
  '/stores': typeof StoresRoute
  '/manager/$storeName': typeof ManagerStoreNameRoute
  '/manager/login': typeof ManagerLoginRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/grocery-list': typeof GroceryListRoute
  '/manager': typeof ManagerRouteWithChildren
  '/shopping-trip': typeof ShoppingTripRoute
  '/stores': typeof StoresRoute
  '/manager/$storeName': typeof ManagerStoreNameRoute
  '/manager/login': typeof ManagerLoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/grocery-list': typeof GroceryListRoute
  '/manager': typeof ManagerRouteWithChildren
  '/shopping-trip': typeof ShoppingTripRoute
  '/stores': typeof StoresRoute
  '/manager/$storeName': typeof ManagerStoreNameRoute
  '/manager/login': typeof ManagerLoginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/chat'
    | '/grocery-list'
    | '/manager'
    | '/shopping-trip'
    | '/stores'
    | '/manager/$storeName'
    | '/manager/login'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/chat'
    | '/grocery-list'
    | '/manager'
    | '/shopping-trip'
    | '/stores'
    | '/manager/$storeName'
    | '/manager/login'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/chat'
    | '/grocery-list'
    | '/manager'
    | '/shopping-trip'
    | '/stores'
    | '/manager/$storeName'
    | '/manager/login'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ChatRoute: typeof ChatRoute
  GroceryListRoute: typeof GroceryListRoute
  ManagerRoute: typeof ManagerRouteWithChildren
  ShoppingTripRoute: typeof ShoppingTripRoute
  StoresRoute: typeof StoresRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stores': {
      id: '/stores'
      path: '/stores'
      fullPath: '/stores'
      preLoaderRoute: typeof StoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shopping-trip': {
      id: '/shopping-trip'
      path: '/shopping-trip'
      fullPath: '/shopping-trip'
      preLoaderRoute: typeof ShoppingTripRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager': {
      id: '/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof ManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grocery-list': {
      id: '/grocery-list'
      path: '/grocery-list'
      fullPath: '/grocery-list'
      preLoaderRoute: typeof GroceryListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/login': {
      id: '/manager/login'
      path: '/login'
      fullPath: '/manager/login'
      preLoaderRoute: typeof ManagerLoginRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/$storeName': {
      id: '/manager/$storeName'
      path: '/$storeName'
      fullPath: '/manager/$storeName'
      preLoaderRoute: typeof ManagerStoreNameRouteImport
      parentRoute: typeof ManagerRoute
    }
  }
}

interface ManagerRouteChildren {
  ManagerStoreNameRoute: typeof ManagerStoreNameRoute
  ManagerLoginRoute: typeof ManagerLoginRoute
}

const ManagerRouteChildren: ManagerRouteChildren = {
  ManagerStoreNameRoute: ManagerStoreNameRoute,
  ManagerLoginRoute: ManagerLoginRoute,
}

const ManagerRouteWithChildren =
  ManagerRoute._addFileChildren(ManagerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ChatRoute: ChatRoute,
  GroceryListRoute: GroceryListRoute,
  ManagerRoute: ManagerRouteWithChildren,
  ShoppingTripRoute: ShoppingTripRoute,
  StoresRoute: StoresRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
